using Stock.Domain.Errors;

namespace Stock.Domain.Entities;

public enum ReplenishmentStatus
{
    Pending,
    Approved,
    Ordered,
    Received,
    Cancelled,
}

/// <summary>Restocking request, created manually by a franchisee or automatically
/// when a stock item falls below its minimum threshold.</summary>
public sealed class ReplenishmentRequest
{
    private static readonly Dictionary<ReplenishmentStatus, ReplenishmentStatus[]> Transitions = new()
    {
        [ReplenishmentStatus.Pending] = [ReplenishmentStatus.Approved, ReplenishmentStatus.Cancelled],
        [ReplenishmentStatus.Approved] = [ReplenishmentStatus.Ordered, ReplenishmentStatus.Cancelled],
        [ReplenishmentStatus.Ordered] = [ReplenishmentStatus.Received, ReplenishmentStatus.Cancelled],
        [ReplenishmentStatus.Received] = [],
        [ReplenishmentStatus.Cancelled] = [],
    };

    private ReplenishmentRequest() { } // EF Core

    public ReplenishmentRequest(Guid tenantId, Guid stockItemId, decimal quantityRequested, string requestedBy, bool isAutomatic = false)
    {
        if (quantityRequested <= 0)
        {
            throw DomainException.Validation("Requested quantity must be greater than zero.");
        }

        Id = Guid.NewGuid();
        TenantId = tenantId;
        StockItemId = stockItemId;
        QuantityRequested = quantityRequested;
        Status = ReplenishmentStatus.Pending;
        RequestedBy = requestedBy;
        IsAutomatic = isAutomatic;
        RequestedAt = DateTimeOffset.UtcNow;
        UpdatedAt = RequestedAt;
    }

    public Guid Id { get; private set; }

    public Guid TenantId { get; private set; }

    public Guid StockItemId { get; private set; }

    public decimal QuantityRequested { get; private set; }

    public ReplenishmentStatus Status { get; private set; }

    public string RequestedBy { get; private set; } = string.Empty;

    /// <summary>True when generated by the low-stock rule rather than a user.</summary>
    public bool IsAutomatic { get; private set; }

    public DateTimeOffset RequestedAt { get; private set; }

    public DateTimeOffset UpdatedAt { get; private set; }

    public void TransitionTo(ReplenishmentStatus target)
    {
        if (!Transitions[Status].Contains(target))
        {
            throw DomainException.InvalidTransition(Status.ToString(), target.ToString());
        }

        Status = target;
        UpdatedAt = DateTimeOffset.UtcNow;
    }
}
